Analytics
turnerlabs/harbor-ui pull request #66
Opened 2018-01-16 20:05 UTC by wilsonodk

Decided to proxy the call to the telemetry service through the app to solve the CORS issue. The extra nice thing about using the proxy is I am able to hide the API key from the UI.

Added integrations with most of the buttons and links. Didn't do anything with links that send folks away from the site.

For most actions I'm capturing both the start and success/failure of the action. Some actions, such as tabs, there is no success or failure.

I don't always capture the Shipment/Environment. I did on Trigger, because I thought it would be useful for debugging.

2018-01-16 20:23 UTC, mickeyyawn approved these changes
LGTM.  Excited about seeing who is using what!!!

2018-01-16 20:36 UTC, jtolsma approved these changes

2018-01-17 17:12 UTC, jritsema approved these changes

2018-01-18 14:54 UTC, jritsema requested changes
Oh, just remembered that talked about adding some new fields to the telemetry api.  We should probably do that before we release this.

2018-01-18 15:15 UTC, wilsonodk commented
@jritsema Yeah, I switched from `ip` to `user` for the NT username. Keep meaning to chat with you about that.

2018-01-24 15:36 UTC, jritsema approved these changes

2018-01-24 15:43 UTC, merged